Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # This line defines the root path route ("/"), which maps to the "home"
  # action of the "pages" controller
  root 'pages#home'

  # This line defines a named route for the "/home" URL path,
  # which maps to the "home" action of the "pages" controller
  get 'home', to: 'pages#home'

  # This line defines a named route for the "/about" URL path,
  # which maps to the "about" action of the "pages" controller
  get 'about', to: 'pages#about'

  # This line defines a resource route for the "articles" resource,
  # which maps HTTP requests to the "ArticlesController".
  # The ":only" option specifies which RESTful actions are available for this resource
  # (in this case, :show, :index, :new, and :create)
  #--------------------------------------------------
  # show: This action displays the details of a single record in the database.
  # It typically maps to a URL like /articles/1, where 1 is the ID of the record being displayed.
  #--------------------------------------------------
  # index: This action displays a list of all records in the database.
  # It typically maps to a URL like /articles.
  #--------------------------------------------------
  # new: This action displays a form for creating a new record in the database.
  # It typically maps to a URL like /articles/new.
  #--------------------------------------------------
  # create: This action processes the data submitted by the form generated by the new action,
  # and creates a new record in the database based on that data.
  # It typically maps to a URL like /articles, and is often implemented as an HTTP POST request.
  resources :articles, only: [:show, :index, :new, :create]
end
